# anacapa-container version of config. copy to Anacapa_db/scripts folder
CUTADAPT="/usr/local/anacapa/anaconda/bin/cutadapt"
MUSCLE="/usr/local/bin/muscle"
MODULE_SOURCE=""
FASTX_TOOLKIT=""
ANACONDA_PYTHON=""
BOWTIE2=""
ATS=""
R=""
PYTHONWNUMPY=""
GCC=""
RUNNER="/opt/singularity-2.4.2/bin/singularity exec -B /act /home/mogden2/anacapa-1.2.0.img /bin/bash"